### ISSUE TITLE
Feature: User can view a random fact about the current day

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a fact about the current day.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Going to the main page displays a random fact of the day from numbers api.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project-issue-1](https://user-images.githubusercontent.com/64382900/137418522-80fce060-8a5c-4e8a-9221-92d816079c9a.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Set up html, css, and script pages
- [ ] Set up html layout
  - [ ] Set up header banner
  - [ ] Set up header date display
  - [ ] set up header button (for future feature view another date)
  - [ ] set up body for containing quote
  - [ ] set up buttons below quote (for future features save quote and request new quote)
  - [ ] set up footer with button (for future feature view calendar)
- [ ] Set up css based off figma wireframe
- [ ] set up script for getting info from numbers api
  - [ ] Detect and save current date to a global variable
  - [ ] generate DOM element in header date display showing today's date using date variable
  - [ ] script requests trivia for today's date using date variable, as JSON
  - [ ] save fact into a fact of the day object
  - [ ] Add listener for when request is loaded, generate DOM element in body to display fact of the day
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
