### ISSUE TITLE
Feature: User can view facts for tomorrow or yesterday without manually selecting day in selector

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/ajax-project#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can press a button to view the fact of the next or previous day.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Add two buttons named "tomorrow" and "yesterday" which can be pressed to change the date by one day

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Add wireframe

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add new buttons
- [ ] Incorporate left or right chevrons on the buttons
- [x] Add listeners for new buttons
- [x] New function that checks date and adds a day or subtracts a day
  - [x] Function also needs to advance to next month or previous month
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] clear the "fact saved!" text when next day is selected
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by DogeThis** [comment]
Will `February 29th` only be reachable this way in certain years?

**Comment by J0N-C** [comment]
Interesting idea, I hadn't considered that. I had figured it would still be able to go to Feb 29 regardless of current year since the random trivia can be from any year as well.
