### ISSUE TITLE
Feature: User can generate new trivia of the day

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can generate new piece of trivia about the day to replace current one

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User presses a button which generates a new piece of trivia for the same day.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project-issue-2 new fact](https://user-images.githubusercontent.com/64382900/137419698-36a8dcda-54b7-4d1d-bfe7-83c3c1bf1b99.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Ensure 'new fact' button has an unique id
- [ ] Add listener for 'new fact' button
- [ ] when 'new fact' button is pressed, a new get request is sent to numbers api for another quote of the day
  - [ ] Perhaps add some way to ensure it is not a duplicate fact? check first few words, and if match, request another? If 2nd one still matches, just display it.
- [ ] use DOM to delete old fact from body and replace with new fact when request is loaded
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by J0N-C** [comment]
![ajax-project-issue-2-generate-new-fact](https://user-images.githubusercontent.com/64382900/137835540-6bdc068d-f525-41b4-bd58-ba45d57b72e3.gif)
