### ISSUE TITLE
Feature: User can view a fact from another date

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select another date to view a fact about that day.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User clicks a button which pops up a date selector by month and day, and the user can view a fact for the selected day or cancel.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project-issue-3 view another day](https://user-images.githubusercontent.com/64382900/137420396-56502d47-726c-4584-aa7f-81654dad1092.JPG)
![ajax-project-issue-3 view another day-desktop](https://user-images.githubusercontent.com/64382900/137422668-34226f8a-a47b-4be9-bbac-e819fd8a035a.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Set up listener for 'view another date' button
- [x] Set up html for modal popup
  - [x] Modal popup is titled 'VIEW NEW DATE'
  - [x] Two dropdown menus, one for selecting month and one for selecting day of month.
  - [x] button labeled 'VIEW DATE' submits selected date dropdown
  - [x] button labeled 'CANCEL' closes the modal
- [x] Set up 'view another date' function
  - [x] Modal popup for date selection is revealed on page 
  - [x] Add listener for 'VIEW DATE' button
  - [x] Collect user inputted dates and request new fact from numbers api with new date  if 'VIEW DATE' is pressed.
  - [x] Update date header to say 'Viewing Date' and display date selected
  - [x] Update body to show new fact for that day
  - [x] Close modal if 'CANCEL' is pressed.
- [x] Pressing banner title returns to home page state which changes date to current day, requests fact for current day and displays it again.  
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by J0N-C** [comment]
![ajax-project-issue-3-view-another-date](https://user-images.githubusercontent.com/64382900/138023380-b5c2c536-663f-4dba-93d5-b27e0f5f5935.gif)
