### ISSUE TITLE
Feature: User can save a fact

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save the currently displayed fact

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
If the user likes the displayed fact, they can press a button to save it.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project-issue-4- SAVE FACT](https://user-images.githubusercontent.com/64382900/137422629-abcfe0d7-218c-4543-bd26-fd5c12ba1dec.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add listener for 'save fact' button
- [ ] Add new empty object for receiving saved facts
- [ ] Ensure saved facts object is saved in local storage and loads back correctly after browser is closed
- [ ] Check if date and fact contents exists in object of saved facts, if yes, do not save.
- [ ] Saving fact saves entire object that was requested from numbers api
- [ ] update body to display to user that fact has been saved.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
