### ISSUE TITLE
Feature: User can view saved facts

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their saved facts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view a calendar list of facts, sorted by month. User selects each month to view. Default is the current month. Empty months cannot be selected.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project-issue-5- view calendar](https://user-images.githubusercontent.com/64382900/137424308-292ecd12-6f1e-4e66-8b0b-58314e0a019d.JPG)
![ajax-project-issue-5- view calendar-desktop](https://user-images.githubusercontent.com/64382900/137424317-53166f3a-70ca-43e0-8e8b-98f46ad86d04.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Set up html for new calendar page
  - [ ] Add buttons labelled with each month of the year to header (mobile) or sidebar (desktop) 
  - [ ] Link calendar page to home page with view calendar button and vice versa with 'back to daily fact' button.
- [ ] set up css for new calendar page month selection
- [ ] Set up script for loading all facts saved for selected month, runs when page loaded.
- [ ] By default load current month
- [ ] By default current month is highlighted
- [ ] Set up listener for when each month is clicked
  - [ ] Run script for loading all facts again, but for selected month
  - [ ] New selected month is highlighted
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by J0N-C** [comment]
![ajax-project-issue-5-user-can-view-saved-facts_mobile](https://user-images.githubusercontent.com/64382900/138391107-7d0bfb5d-a9d5-4b2d-9200-50af419104aa.gif)
![ajax-project-issue-5-user-can-view-saved-facts](https://user-images.githubusercontent.com/64382900/138391114-3af63d88-0c20-4842-b9f3-18b773b70ea5.gif)
