### ISSUE TITLE
Feature: User can delete facts from calendar of facts

### ISSUE THREAD

**Issue by J0N-C** [J0N-C/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a fact they saved in the calendar

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can press a button to delete selected fact from their calendar of saved facts

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project-issue-6- delete fact](https://user-images.githubusercontent.com/64382900/137424713-acf52e34-fb93-4d1c-bd89-c645cd962a6e.JPG)
![ajax-project-issue-6- delete fact-desktop](https://user-images.githubusercontent.com/64382900/137424722-b84472ce-6e6d-4799-96e3-71a616fc6472.JPG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When each fact is loaded into daily list for the month on calendar, also generate a 'delete fact' button
- [x] Add html for confirming delete to calendar page, hidden until needed
- [x] Add listener for 'delete fact' button
  - [x] Clicking this reveals confirmation popup to delete 
  - [x] When confirm is clicked, deletes fact from facts object
  - [x] Delete selected DOM element displaying that fact 
  - [x] Clicking cancel closes confirmation
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by J0N-C** [comment]
![ajax-project-issue-6- delete fact](https://user-images.githubusercontent.com/64382900/140012525-2e18c522-3c34-475c-b2cb-6c2d7d3de693.JPG)
